In [2]:
import pandas as pd

destinations = pd.read_csv("data/destinations.csv")
train = pd.read_csv("data/train.csv")
test= pd.read_csv("data/test.csv")

In [3]:
test.shape

(2528243, 22)

In [4]:
train.shape

(37670293, 24)

In [7]:
train.head(5)

,date_time,site_name,posa_continent,user_location_country,user_location_region,user_location_city,orig_destination_distance,user_id,is_mobile,is_package,...,srch_children_cnt,srch_rm_cnt,srch_destination_id,srch_destination_type_id,is_booking,cnt,hotel_continent,hotel_country,hotel_market,hotel_cluster
0,2014-08-11 07:46:59,2,3,66,348,48862,2234.2641,12,0,1,...,0,1,8250,1,0,3,2,50,628,1
1,2014-08-11 08:22:12,2,3,66,348,48862,2234.2641,12,0,1,...,0,1,8250,1,1,1,2,50,628,1
2,2014-08-11 08:24:33,2,3,66,348,48862,2234.2641,12,0,0,...,0,1,8250,1,0,1,2,50,628,1
3,2014-08-09 18:05:16,2,3,66,442,35390,913.1932,93,0,0,...,0,1,14984,1,0,1,2,50,1457,80
4,2014-08-09 18:08:18,2,3,66,442,35390,913.6259,93,0,0,...,0,1,14984,1,0,1,2,50,1457,21

In [8]:
test.head(5)

,id,date_time,site_name,posa_continent,user_location_country,user_location_region,user_location_city,orig_destination_distance,user_id,is_mobile,...,srch_ci,srch_co,srch_adults_cnt,srch_children_cnt,srch_rm_cnt,srch_destination_id,srch_destination_type_id,hotel_continent,hotel_country,hotel_market
0,0,2015-09-03 17:09:54,2,3,66,174,37449,5539.0567,1,1,...,2016-05-19,2016-05-23,2,0,1,12243,6,6,204,27
1,1,2015-09-24 17:38:35,2,3,66,174,37449,5873.2923,1,1,...,2016-05-12,2016-05-15,2,0,1,14474,7,6,204,1540
2,2,2015-06-07 15:53:02,2,3,66,142,17440,3975.9776,20,0,...,2015-07-26,2015-07-27,4,0,1,11353,1,2,50,699
3,3,2015-09-14 14:49:10,2,3,66,258,34156,1508.5975,28,0,...,2015-09-14,2015-09-16,2,0,1,8250,1,2,50,628
4,4,2015-07-17 09:32:04,2,3,66,467,36345,66.7913,50,0,...,2015-07-22,2015-07-23,2,0,1,11812,1,2,50,538

In [9]:
train.hotel_cluster.value_counts()

91    1043720
41     772743
48     754033
64     704734
65     670960
5      620194
98     589178
59     570291
42     551605
21     550092
70     545572
18     545284
83     534132
46     534038
25     530591
62     518809
95     509266
28     507016
68     503797
82     503755
37     496061
50     489892
30     489287
9      488328
58     483253
97     479446
16     477868
72     457463
1      452694
99     444887
       ...
19     282893
84     278264
66     273505
38     269246
87     260398
23     259233
12     259022
31     257587
67     255946
43     253578
7      252447
54     250745
92     244343
89     243560
45     241408
49     240124
3      225250
80     220218
60     217919
71     216054
93     214293
86     209054
14     192299
75     165226
24     164127
35     139122
53     134812
88     107784
27     105040
74      48355
dtype: int64

In [11]:
test_ids = set(test.user_id.unique())
train_ids = set(train.user_id.unique())
inters_count = (test_ids & train_ids)
print len(inters_count)
print len(test_ids)
print len(train_ids)

1181577
1181577
1198786

In [14]:
train.date_time =pd.to_datetime(train.date_time)

In [27]:
train["year"] = train.date_time.dt.year
train["month"] = train.date_time.dt.month

In [29]:
import random 
unique_user = train.user_id.unique()

sel_user_ids = [unique_user[i] for i in sorted(random.sample(range(len(unique_user)),10000))]
sel_train = train[train.user_id.isin(sel_user_ids)]

In [66]:
t1 = sel_train[((sel_train.year == 2013) | ((sel_train.year == 2014) & (sel_train.month < 8)))]
t2 = sel_train[((sel_train.year == 2014) & (sel_train.month >= 8))]

In [31]:
t1.head(10)

,date_time,site_name,posa_continent,user_location_country,user_location_region,user_location_city,orig_destination_distance,user_id,is_mobile,is_package,...,srch_destination_id,srch_destination_type_id,is_booking,cnt,hotel_continent,hotel_country,hotel_market,hotel_cluster,year,month
4367,2014-01-21 13:22:58,2,3,66,149,8559,1708.6801,26981,0,1,...,8279,1,0,1,2,50,1230,70,2014,1
4368,2014-02-06 19:11:06,2,3,66,149,8559,4070.3136,26981,0,1,...,8859,1,0,7,2,50,212,84,2014,2
4369,2014-02-06 19:17:37,2,3,66,149,8559,4065.3495,26981,0,1,...,8859,1,0,2,2,50,212,26,2014,2
4370,2014-02-06 19:33:16,2,3,66,149,8559,4084.8291,26981,0,1,...,8859,1,0,2,2,50,212,8,2014,2
4371,2014-02-06 19:35:41,2,3,66,149,8559,4084.8508,26981,0,1,...,8859,1,0,1,2,50,212,89,2014,2
4372,2014-02-06 19:37:37,2,3,66,149,8559,4070.3069,26981,0,1,...,8859,1,0,1,2,50,212,56,2014,2
4373,2014-02-06 19:40:17,2,3,66,149,8559,4070.4208,26981,0,1,...,8859,1,0,1,2,50,212,97,2014,2
4374,2014-02-06 19:43:37,2,3,66,149,8559,4070.4060,26981,0,1,...,8859,1,0,1,2,50,212,92,2014,2
4375,2014-02-06 19:45:32,2,3,66,149,8559,4070.4440,26981,0,1,...,8859,1,0,5,2,50,212,0,2014,2
4376,2014-02-06 19:49:47,2,3,66,149,8559,864.7310,26981,0,1,...,14875,1,0,7,2,198,750,95,2014,2

In [67]:
t2 = t2[t2.is_booking==True]

In [33]:
t2.head(20)

,date_time,site_name,posa_continent,user_location_country,user_location_region,user_location_city,orig_destination_distance,user_id,is_mobile,is_package,...,srch_destination_id,srch_destination_type_id,is_booking,cnt,hotel_continent,hotel_country,hotel_market,hotel_cluster,year,month
4396,2014-11-03 11:16:50,2,3,66,149,8559,440.1759,26981,0,0,...,8243,1,1,1,2,50,409,59,2014,11
4402,2014-12-17 14:08:43,2,3,66,149,8559,1429.8555,26981,0,1,...,1152,1,1,1,4,47,1502,73,2014,12
33043,2014-12-13 23:00:03,35,2,70,50,26680,NaN,128963,0,0,...,8747,1,1,1,3,106,107,48,2014,12
33045,2014-12-13 23:11:20,35,2,70,50,26680,NaN,128963,0,0,...,8744,1,1,1,3,106,108,15,2014,12
37137,2014-10-16 12:27:53,11,3,205,339,36801,NaN,143141,0,0,...,12547,5,1,1,3,106,107,90,2014,10
37144,2014-10-16 13:36:24,11,3,205,339,36801,NaN,143141,0,0,...,8744,1,1,1,3,106,108,47,2014,10
37146,2014-11-04 08:43:01,11,3,205,339,36801,NaN,143141,0,1,...,8262,1,1,1,2,198,384,28,2014,11
37149,2014-12-03 19:27:15,11,3,205,339,36801,NaN,143141,0,0,...,8262,1,1,1,2,198,384,28,2014,12
40186,2014-10-14 09:21:54,2,3,66,174,12485,79.3871,152497,0,0,...,8838,1,1,1,2,50,363,90,2014,10
42481,2014-08-09 15:55:38,40,3,66,442,47956,1758.8178,159401,0,0,...,8288,1,1,1,2,198,399,72,2014,8
45213,2014-10-07 14:22:53,2,3,66,331,35714,1807.8915,166437,0,1,...,12019,1,1,1,4,186,209,63,2014,10
46189,2014-08-19 16:24:53,2,3,66,337,6599,1622.4074,170605,0,1,...,12257,6,1,1,4,51,1509,47,2014,8
67577,2014-08-14 11:10:29,2,3,66,220,4948,654.7287,249648,0,0,...,5152,3,1,1,2,50,678,48,2014,8
71160,2014-08-11 15:01:09,2,3,66,474,26179,NaN,275231,0,0,...,484,1,1,1,2,50,631,91,2014,8
71216,2014-12-13 20:51:38,2,3,66,174,52320,2414.8555,275231,0,0,...,13441,4,1,1,2,50,682,47,2014,12
71218,2014-12-13 20:59:49,2,3,66,174,52320,2338.0649,275231,0,0,...,33920,1,1,1,2,50,460,47,2014,12
71222,2014-12-13 21:26:20,2,3,66,174,52320,2564.5430,275231,0,0,...,4586,3,1,1,2,50,701,42,2014,12
71233,2014-12-15 16:15:12,2,3,66,174,52320,2560.4553,275231,0,0,...,12495,5,1,1,2,50,699,48,2014,12
82892,2014-10-16 20:32:02,24,2,3,50,5224,NaN,333973,0,0,...,41960,6,1,1,3,106,107,3,2014,10
83000,2014-10-02 17:40:09,11,3,205,385,19323,NaN,334851,0,0,...,4454,3,1,1,2,50,682,71,2014,10

In [35]:
most_common_cl = list(train.hotel_cluster.value_counts().head().index)

In [36]:
predictions = [most_common_cl for i in range(t2.shape[0])]

In [37]:
predictions

[[91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],
 [91, 41, 48, 64, 65],

In [40]:
import ml_metrics as metrics

target = [[l] for l in t2.hotel_cluster]
metrics.mapk(target,predictions,k=5)

0.057517074795935152

In [41]:
train.corr()["hotel_cluster"]

site_name                   -0.022408
posa_continent               0.014938
user_location_country       -0.010477
user_location_region         0.007453
user_location_city           0.000831
orig_destination_distance    0.007260
user_id                      0.001052
is_mobile                    0.008412
is_package                   0.038733
channel                      0.000707
srch_adults_cnt              0.012309
srch_children_cnt            0.016261
srch_rm_cnt                 -0.005954
srch_destination_id         -0.011712
srch_destination_type_id    -0.032850
is_booking                  -0.021548
cnt                          0.002944
hotel_continent             -0.013963
hotel_country               -0.024289
hotel_market                 0.034205
hotel_cluster                1.000000
year                        -0.001050
month                       -0.000560
Name: hotel_cluster, dtype: float64

In [50]:
from sklearn.decomposition import PCA

pca = PCA(n_components=3)
dest_small = pca.fit_transform(destinations[["d{0}".format(i+1) for i in range(149)]])
dest_small = pd.DataFrame(dest_small)
dest_small["srch_destination_id"] = destinations.srch_destination_id

In [51]:
def calc_fast_features(df):
    df["date_time"] = pd.to_datetime(df["date_time"])
    df["srch_ci"] = pd.to_datetime(df["srch_ci"], format='%Y-%m-%d', errors="coerce")
    df["srch_co"] = pd.to_datetime(df["srch_co"], format='%Y-%m-%d', errors="coerce")
    
    props = {}
    for prop in ["month", "day", "hour", "minute", "dayofweek", "quarter"]:
        props[prop] = getattr(df["date_time"].dt, prop)
    
    carryover = [p for p in df.columns if p not in ["date_time", "srch_ci", "srch_co"]]
    for prop in carryover:
        props[prop] = df[prop]
    
    date_props = ["month", "day", "dayofweek", "quarter"]
    for prop in date_props:
        props["ci_{0}".format(prop)] = getattr(df["srch_ci"].dt, prop)
        props["co_{0}".format(prop)] = getattr(df["srch_co"].dt, prop)
    props["stay_span"] = (df["srch_co"] - df["srch_ci"]).astype('timedelta64[h]')
        
    ret = pd.DataFrame(props)
    
    ret = ret.join(dest_small, on="srch_destination_id", how='left', rsuffix="dest")
    ret = ret.drop("srch_destination_iddest", axis=1)
    return ret

In [52]:
df = calc_fast_features(t1)
df.fillna(-1, inplace=True)

/Library/Python/2.7/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
/Library/Python/2.7/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
/Library/Python/2.7/site-packages/ipykernel/__main__.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [53]:
predictors = [c for c in df.columns if c not in ["hotel_cluster"]]
from sklearn import cross_validation
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(n_estimators=10, min_weight_fraction_leaf=0.1)
scores = cross_validation.cross_val_score(clf, df[predictors], df['hotel_cluster'], cv=3)
scores

array([ 0.06633958,  0.06752789,  0.07053648])

In [81]:
groups.head()

,date_time,site_name,posa_continent,user_location_country,user_location_region,user_location_city,orig_destination_distance,user_id,is_mobile,is_package,...,srch_destination_id,srch_destination_type_id,is_booking,cnt,hotel_continent,hotel_country,hotel_market,hotel_cluster,year,month
4367,2014-01-21 13:22:58,2,3,66,149,8559,1708.6801,26981,0,1,...,8279,1,0,1,2,50,1230,70,2014,1
4368,2014-02-06 19:11:06,2,3,66,149,8559,4070.3136,26981,0,1,...,8859,1,0,7,2,50,212,84,2014,2
4369,2014-02-06 19:17:37,2,3,66,149,8559,4065.3495,26981,0,1,...,8859,1,0,2,2,50,212,26,2014,2
4370,2014-02-06 19:33:16,2,3,66,149,8559,4084.8291,26981,0,1,...,8859,1,0,2,2,50,212,8,2014,2
4371,2014-02-06 19:35:41,2,3,66,149,8559,4084.8508,26981,0,1,...,8859,1,0,1,2,50,212,89,2014,2
4372,2014-02-06 19:37:37,2,3,66,149,8559,4070.3069,26981,0,1,...,8859,1,0,1,2,50,212,56,2014,2
4373,2014-02-06 19:40:17,2,3,66,149,8559,4070.4208,26981,0,1,...,8859,1,0,1,2,50,212,97,2014,2
4374,2014-02-06 19:43:37,2,3,66,149,8559,4070.4060,26981,0,1,...,8859,1,0,1,2,50,212,92,2014,2
4375,2014-02-06 19:45:32,2,3,66,149,8559,4070.4440,26981,0,1,...,8859,1,0,5,2,50,212,0,2014,2
4376,2014-02-06 19:49:47,2,3,66,149,8559,864.7310,26981,0,1,...,14875,1,0,7,2,198,750,95,2014,2
4377,2014-02-06 19:52:38,2,3,66,149,8559,864.7025,26981,0,1,...,14875,1,0,4,2,198,750,21,2014,2
4378,2014-02-06 19:55:57,2,3,66,149,8559,864.7310,26981,0,1,...,14875,1,0,5,2,198,750,95,2014,2
4379,2014-02-06 20:00:27,2,3,66,149,8559,864.7310,26981,0,0,...,14875,1,0,1,2,198,750,95,2014,2
4380,2014-02-26 09:41:28,2,3,66,149,8559,97.3456,26981,0,0,...,26424,1,0,1,2,50,496,91,2014,2
4381,2014-02-26 09:42:14,2,3,66,149,8559,97.6010,26981,0,0,...,26424,1,0,1,2,50,496,3,2014,2
4382,2014-02-26 09:54:42,2,3,66,149,8559,92.2794,26981,0,0,...,26442,6,0,2,2,50,496,18,2014,2
4383,2014-02-26 09:56:11,2,3,66,149,8559,92.2794,26981,0,0,...,26442,6,0,1,2,50,496,18,2014,2
4384,2014-02-26 09:56:44,2,3,66,149,8559,97.3456,26981,0,0,...,26442,6,0,1,2,50,496,91,2014,2
4385,2014-02-26 17:20:24,2,3,66,149,8559,82.1388,26981,0,0,...,19685,1,0,1,2,50,635,29,2014,2
4386,2014-02-26 17:22:59,2,3,66,149,8559,82.2297,26981,0,0,...,19685,1,0,1,2,50,635,48,2014,2
4387,2014-02-27 09:54:07,2,3,66,149,8559,129.3694,26981,0,0,...,26663,1,0,1,2,50,707,73,2014,2
4388,2014-02-27 09:54:58,2,3,66,149,8559,130.3020,26981,0,0,...,26663,1,0,1,2,50,707,63,2014,2
4389,2014-02-27 10:01:23,2,3,66,149,8559,133.1857,26981,0,0,...,26663,1,0,1,2,50,707,71,2014,2
4390,2014-02-27 10:02:41,2,3,66,149,8559,128.5956,26981,0,0,...,26663,1,0,1,2,50,707,18,2014,2
4391,2014-05-22 13:01:39,2,3,66,149,8559,85.5749,26981,0,0,...,26595,3,0,1,2,50,496,90,2014,5
6040,2013-07-10 17:34:28,25,2,23,48,4924,NaN,35452,0,0,...,8822,1,0,1,3,130,1706,36,2013,7
6041,2013-07-10 20:32:39,25,2,23,48,4924,NaN,35452,0,0,...,8822,1,0,3,3,130,1706,36,2013,7
6042,2013-07-10 21:12:41,25,2,23,48,4924,NaN,35452,0,0,...,8822,1,0,1,3,130,1706,36,2013,7
12672,2013-10-04 20:05:45,37,1,69,727,43458,NaN,70059,0,0,...,6393,6,0,1,6,70,1921,90,2013,10
12673,2013-10-04 20:12:31,37,1,69,727,43458,NaN,70059,0,0,...,6393,6,0,1,6,70,1921,32,2013,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37657943,2013-09-16 10:21:58,2,3,66,337,30384,1332.1770,1144255,0,0,...,8235,1,0,1,2,50,406,21,2013,9
37657944,2013-09-16 10:22:54,2,3,66,337,30384,1332.2337,1144255,0,0,...,8235,1,0,1,2,50,406,33,2013,9
37657945,2013-09-16 10:23:28,2,3,66,337,30384,1332.7469,1144255,0,0,...,8235,1,0,1,2,50,406,4,2013,9
37657946,2013-09-16 10:28:50,2,3,66,337,30384,1328.6424,1144255,0,0,...,8235,1,0,1,2,50,406,19,2013,9
37657947,2013-09-16 10:32:45,2,3,66,337,30384,1333.4419,1144255,0,0,...,8235,1,0,1,2,50,406,68,2013,9
37657948,2013-10-02 09:26:04,2,3,66,337,15717,47.8210,1144255,0,0,...,11569,1,0,1,2,50,623,21,2013,10
37657949,2013-12-11 11:18:47,2,3,66,337,27268,66.1661,1144255,0,0,...,11569,1,0,1,2,50,623,83,2013,12
37657950,2013-12-11 11:20:14,2,3,66,337,27268,61.6454,1144255,0,0,...,11569,1,0,1,2,50,623,47,2013,12
37657951,2013-12-11 11:24:09,2,3,66,337,27268,61.6046,1144255,0,0,...,11569,1,0,1,2,50,623,42,2013,12
37657952,2014-02-03 15:30:50,2,3,66,363,31138,2193.2368,1144255,0,0,...,8250,1,0,5,2,50,628,71,2014,2
37657953,2014-02-03 15:39:28,2,3,66,363,31138,2193.2368,1144255,0,1,...,8250,1,0,3,2,50,628,71,2014,2
37657954,2014-02-23 16:18:58,2,3,66,337,27268,2204.2464,1144255,0,1,...,8250,1,0,2,2,50,628,71,2014,2
37657955,2014-02-26 09:16:06,2,3,66,337,27268,2204.2464,1144255,0,1,...,8250,1,0,1,2,50,628,71,2014,2
37657956,2014-02-26 16:37:30,2,3,66,363,31138,2193.2368,1144255,0,1,...,8250,1,0,2,2,50,628,71,2014,2
37657957,2014-02-26 16:39:41,2,3,66,363,31138,2193.2368,1144255,0,1,...,8250,1,0,3,2,50,628,71,2014,2
37657958,2014-02-26 16:57:36,2,3,66,363,31138,2193.2368,1144255,0,1,...,8250,1,0,1,2,50,628,71,2014,2
37657959,2014-02-27 07:11:41,2,3,66,337,27268,2204.2303,1144255,0,1,...,8250,1,0,2,2,50,628,51,2014,2
37657960,2014-02-27 07:16:06,2,3,66,337,27268,2202.9033,1144255,0,1,...,8250,1,0,6,2,50,628,18,2014,2
37657961,2014-02-27 10:01:28,2,3,66,337,27268,2202.5309,1144255,0,1,...,8250,1,0,1,2,50,628,91,2014,2
37657962,2014-02-27 10:03:47,2,3,66,337,27268,2205.3940,1144255,0,1,...,8250,1,0,1,2,50,628,94,2014,2
37657963,2014-02-27 10:05:07,2,3,66,337,27268,2206.4608,1144255,0,1,...,8250,1,0,2,2,50,628,71,2014,2
37657964,2014-04-06 19:59:17,2,3,66,363,31138,2189.3740,1144255,0,0,...,8250,1,0,1,2,50,628,94,2014,4
37657965,2014-05-19 09:21:49,2,3,66,363,31138,124.3695,1144255,0,0,...,63067,6,0,1,2,50,695,40,2014,5
37657966,2014-06-14 18:59:19,2,3,66,363,31138,224.1076,1144255,0,0,...,33251,4,0,1,2,50,692,3,2014,6
37657967,2014-06-14 19:00:50,2,3,66,363,31138,221.2123,1144255,0,0,...,33251,4,0,1,2,50,611,16,2014,6
37657968,2014-06-14 19:03:37,2,3,66,363,31138,220.3473,1144255,0,0,...,33251,4,0,1,2,50,611,40,2014,6
37657969,2014-06-14 19:04:24,2,3,66,363,31138,220.0847,1144255,0,0,...,33251,4,0,1,2,50,611,42,2014,6
37659267,2013-03-15 13:52:05,2,3,66,174,9444,2108.3530,1147484,0,1,...,12188,6,0,16,4,8,110,87,2013,3
37659268,2013-03-15 15:03:36,2,3,66,174,9444,2108.3530,1147484,0,1,...,12188,6,1,1,4,8,110,87,2013,3
37659270,2014-07-21 20:00:08,2,3,66,174,21183,1686.5917,1147484,0,1,...,8266,1,0,2,2,50,411,9,2014,7

In [94]:
#define the train and test for final results
t1 = train
t2 = test

def make_key(items):
    return "_".join([str(i) for i in items])

#clusters by destination id and type
match_cols = ["srch_destination_id", "srch_destination_type_id", "is_package", "hotel_market"]
cluster_cols = match_cols + ['hotel_cluster']
groups = t1.groupby(cluster_cols)
top_clusters = {}
for name, group in groups:
    clicks = len(group.is_booking[group.is_booking == False])
    bookings = len(group.is_booking[group.is_booking == True])
    
    score = bookings + .15 * clicks
    
    clus_name = make_key(name[:len(match_cols)])
    if clus_name not in top_clusters:
        top_clusters[clus_name] = {}
    top_clusters[clus_name][name[-1]] = score

In [95]:
import operator

cluster_dict = {}
for n in top_clusters:
    tc = top_clusters[n]
    top = [l[0] for l in sorted(tc.items(), key=operator.itemgetter(1), reverse=True)[:5]]
    cluster_dict[n] = top

In [96]:
#t2=test 

preds = []
for index, row in t2.iterrows():
    key = make_key([row[m] for m in match_cols])
    if key in cluster_dict:
        preds.append(cluster_dict[key])
    else:
        preds.append([])

In [60]:
t2.to_csv("submission_test.csv")

In [98]:
metrics.mapk([[l] for l in t2["hotel_clusters"]], preds, k=5)

KeyError: 'hotel_clusters'

In [99]:
match_cols = ['user_location_country', 'user_location_region', 'user_location_city', 
              'hotel_market', 'orig_destination_distance']

groups = t1.groupby(match_cols)
    
def generate_exact_matches(row, match_cols):
    index = tuple([row[t] for t in match_cols])
    try:
        group = groups.get_group(index)
    except Exception:
        return []
    clus = list(set(group.hotel_cluster))
    return clus

exact_matches = []
for i in range(t2.shape[0]):
    exact_matches.append(generate_exact_matches(t2.iloc[i], match_cols))

KeyboardInterrupt:

In [92]:
def f5(seq, idfun=None): 
    if idfun is None:
        def idfun(x): return x
    seen = {}
    result = []
    for item in seq:
        marker = idfun(item)
        if marker in seen: continue
        seen[marker] = 1
        result.append(item)
    return result
    
full_preds = [f5(exact_matches[p] + preds[p] + most_common_cl)[:5] for p in range(len(preds))]
metrics.mapk([[l] for l in t2["hotel_cluster"]], full_preds, k=5)

0.26669998334166206

In [93]:


write_p = [" ".join([str(l) for l in p]) for p in preds]
write_frame = ["{0},{1}".format(t2["id"][i], write_p[i]) for i in range(len(preds))]
write_frame = ["id,hotel_cluster"] + write_frame
with open("predictions_v2.csv", "w+") as f:
    f.write("\n".join(write_frame))

KeyError: 'id'